name: Release Binaries

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Linux
          - goos: linux
            goarch: amd64
            output_name: ocp-doc-checker-linux-amd64
          - goos: linux
            goarch: arm64
            output_name: ocp-doc-checker-linux-arm64
          # macOS
          - goos: darwin
            goarch: amd64
            output_name: ocp-doc-checker-darwin-amd64
          - goos: darwin
            goarch: arm64
            output_name: ocp-doc-checker-darwin-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          COMMIT=$(git rev-parse --short HEAD)
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          
          go build \
            -ldflags="-X 'main.version=${VERSION}' -X 'main.commit=${COMMIT}' -X 'main.date=${DATE}'" \
            -o ${{ matrix.output_name }} \
            .

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.output_name }}
          path: ${{ matrix.output_name }}

  upload:
    name: Upload Binaries to Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v5
        with:
          path: binaries

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: binaries/**/*

